#include "pile/pile.h"
#include <stdlib.h>
#include <stdio.h>
#include <stdbool.h>
bool test_creer_pile();
bool push_pile_vide();
bool push_pile_non_vide();
bool push_pile_avec_5000éléments();
void push_pile_avec_5000_élément_vérification_des_valeurs();
void pop_pile_vide();
void pop_pile_3_elements();
void push_pile_avec_5000_element_verification_des_valeurs();
void values_pile_avec_5000_element_verification_des_valeurs();
void lenght_pile_avec_5000_element_verification_des_valeurs();
void test_values_pile_avec_5000_element_verification_des_valeurss();